# Generated by Django 5.0 on 2024-01-06 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='alt_kategoriler',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='kategori',
        ),
        migrations.DeleteModel(
            name='AltKategoriler',
        ),
        migrations.DeleteModel(
            name='Kategori',
        ),
        migrations.DeleteModel(
            name='ToDo',
        ),
    ]
